baseURL = 'https://pyguru.org'
copyright = 'Idan Hazan © 2024'
theme = 'PaperMod'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[outputs]
  home = ['html', 'rss', 'json']
[params]
  env = 'production'
  author = 'Idan Hazan'
  defaultTheme = 'auto'
  displayFullLangName = true
  ShowCodeCopyButtons = true
  comments = true
[markup.highlight]
  noClasses  = true
  lineNos = true
  lineNumbersInTable = false
  style = 'onedark'
[params.fuseOpts]
  isCaseSensitive = false
  includeScore = false
  includeMatches = false
  minMatchCharLength = 1
  shouldSort = true
  findAllMatches = true
  keys = ['title', 'permalink', 'summary', 'content']
  location = 0
  threshold = 0.0
  distance = 100
  ignoreLocation = true
[languages.en]
  contentDir = 'content/en'
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  title = 'PyGuru'
  weight = 1
[languages.he]
  contentDir = 'content/he'
  disabled = false
  languageCode = 'he-IL'
  languageDirection = 'rtl'
  languageName = 'Hebrew'
  title = 'פייגורו'
  weight = 2
[[languages.en.menu.main]]
  name = 'Search'
  url = '/en/search'
  weight = 1
[[languages.he.menu.main]]
  name = 'חיפוש'
  url = '/he/search'
  weight = 1
[params.profileMode]
  enabled = true
  imageUrl = '/images/logo.png'
  imageWidth = 400
  imageHeight = 400
[languages.en.params.profileMode]
  subtitle = 'From Basics to Mastery: In-Depth Python Learning'
[languages.he.params.profileMode]
  subtitle = 'מהיסודות ועד לשליטה מלאה: למידה מעמיקה בפייתון'
[[params.socialIcons]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/idanhazan'
[[params.socialIcons]]
  name = 'GitHub'
  url = 'https://github.com/idanhazan'
[[languages.en.params.profileMode.buttons]]
  name = 'Discover Python'
  url = '/en/introduction'
[[languages.he.params.profileMode.buttons]]
  name = 'גלה את פייתון'
  url = '/he/introduction'