baseURL = "https://pyguru.org"
title = "PyGuru"
copyright = "Idan Hazan © 2024"
theme = "PaperMod"
mainSections = ["topics"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[outputs]
  home = ["html", "rss", "json"]
[permalinks]
  tags = "/tags/:slug/"
[params]
  env = "production"
  defaultTheme = "auto"
  displayFullLangName = true
  showCodeCopyButtons = true
  showBreadCrumbs = true
  showReadingTime = true
  showWordCount = true
  showToc = true
  tocOpen = false
  showPostNavLinks = true
  comments = true
[params.editPost]
  url = "https://github.com/idanhazan/pyguru/tree/main/content/he"
  appendFilePath = true
[markup.highlight]
  noClasses  = true
  lineNos = true
  lineNumbersInTable = false
  style = "onedark"
[params.fuseOpts]
  isCaseSensitive = false
  includeScore = false
  includeMatches = false
  minMatchCharLength = 1
  shouldSort = true
  findAllMatches = true
  keys = ["title", "content"]
  location = 0
  threshold = 0.0
  distance = 100
  ignoreLocation = true
[languages.en]
  contentDir = "content/en"
  languageCode = "en-US"
  languageDirection = "ltr"
  languageName = "English"
  weight = 1
[languages.he]
  contentDir = "content/he"
  disabled = false
  languageCode = "he-IL"
  languageDirection = "rtl"
  languageName = "Hebrew"
  weight = 2
[[languages.en.menu.main]]
  name = "Categories"
  url = "/en/categories"
  weight = 1
[[languages.he.menu.main]]
  name = "קטגוריות"
  url = "/he/categories"
  weight = 1
[[languages.en.menu.main]]
  name = "Tags"
  url = "/en/tags"
  weight = 2
[[languages.he.menu.main]]
  name = "תגיות"
  url = "/he/tags"
  weight = 2
[[languages.en.menu.main]]
  name = "Search"
  url = "/en/search"
  weight = 3
[[languages.he.menu.main]]
  name = "חיפוש"
  url = "/he/search"
  weight = 3
[params.profileMode]
  enabled = true
  imageUrl = "/images/logo.png"
  imageWidth = 350
  imageHeight = 350
[languages.en.params.profileMode]
  subtitle = "From Basics to Mastery: In-Depth Python Learning"
[languages.he.params.profileMode]
  subtitle = "מהיסודות ועד לשליטה מלאה: למידה מעמיקה בפייתון"
[[params.socialIcons]]
  name = "Telegram"
  url = "https://t.me/idanhazan"
[[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/idanhazan"
[[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/idanhazan"
[[languages.en.params.profileMode.buttons]]
  name = "Discover Python"
  url = "/en/topics"
[[languages.he.params.profileMode.buttons]]
  name = "גלה את פייתון"
  url = "/he/topics"