baseURL = 'http://localhost:1313/'
theme = 'PaperMod'
[languages.en]
  contentDir = 'content/en'
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  title = 'PyGuru'
  weight = 2
[languages.he]
  contentDir = 'content/he'
  disabled = false
  languageCode = 'he-IL'
  languageDirection = 'rtl'
  languageName = 'Hebrew'
  title = 'פייגורו'
  weight = 1
[[languages.en.menu.main]]
  name = 'Search'
  url = '/search/'
  weight = 1
[[languages.he.menu.main]]
  name = 'חיפוש'
  url = '/search/'
  weight = 1
[params.profileMode]
  enabled = true
  imageUrl = '/images/logo.png'
  imageWidth = 512
  imageHeight = 512
[languages.en.params.profileMode]
  title = 'Title'
  subtitle = 'Subtitle'
[languages.he.params.profileMode]
  title = 'כותרת'
  subtitle = 'כותרת משנה'
[[params.socialIcons]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/idanhazan'
[[params.socialIcons]]
  name = 'GitHub'
  url = 'https://github.com/idanhazan'
[[languages.en.params.profileMode.buttons]]
  name = 'Button'
  url = '/somewhere/'
[[languages.he.params.profileMode.buttons]]
  name = 'כפתור'
  url = '/somewhere/'