name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.133.1'

      - name: Clone PaperMod Theme with Depth
        run: git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod themes/PaperMod

      - name: Add PaperMod Theme as Submodule
        run: git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod

      - name: Initialize and Update Submodules Recursively
        run: git submodule update --init --recursive

      - name: Install Hugo Modules
        run: hugo mod get -u

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
