name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

#      - name: Clone PaperMod Theme with Depth
#        run: git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod themes/PaperMod
#
#      - name: Add PaperMod Theme as Submodule
#        run: git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
#
#      - name: Initialize and Update Submodules Recursively
#        run: git submodule update --init --recursive

      - name: Install Hugo Modules
        run: hugo mod get -u

      - name: Build site
        run: hugo --gc --minify

      - name: Add CNAME file
        run: echo 'pyguru.org' > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          publish_dir: ./public
